export const sampleBank3Units = [
    {"id":"3Q01","units":3,"question":"פתור: 3x-7=11.","template_hint":"T3-ALG-LINEAR-QUAD"},
    {"id":"3Q02","units":3,"question":"פתור: x^2-5x+6=0.","template_hint":"T3-ALG-LINEAR-QUAD"},
    {"id":"3Q03","units":3,"question":"פתור מערכת: {2x+y=7, x-y=1}.","template_hint":"T3-ALG-SYSTEMS"},
    {"id":"3Q04","units":3,"question":"נתונה הפונקציה y=2x-3. מצא חיתוך עם הצירים.","template_hint":"T3-FUNC-LINE-PARABOLA"},
    {"id":"3Q05","units":3,"question":"נתונה הפונקציה y=x^2-4x+1. מצא קודקוד וחיתוך עם ציר x.","template_hint":"T3-FUNC-LINE-PARABOLA"},
    {"id":"3Q06","units":3,"question":"תאר את ההזזה של y=(x-2)^2+3 ביחס ל-y=x^2.","template_hint":"T3-FUNC-TRANSFORMS"},
    {"id":"3Q07","units":3,"question":"במשולש ישר זווית, יתר=10 וניצב=6. מצא זווית חדה באמצעות sin/cos.","template_hint":"T3-TRIG-RIGHT-TRI"},
    {"id":"3Q08","units":3,"question":"במשולש ישר זווית, tan(θ)=3/4. מצא sin(θ) ו-cos(θ).","template_hint":"T3-TRIG-RIGHT-TRI"},
    {"id":"3Q09","units":3,"question":"במשולש, ישר מקביל לצלע אחת חותך את השתיים האחרות. מצא יחס קטעים (תלס).","template_hint":"T3-GEO-SIMILARITY-THALES"},
    {"id":"3Q10","units":3,"question":"נתון ΔABC ~ ΔADE. מצא אורך חסר לפי יחס דמיון.","template_hint":"T3-GEO-SIMILARITY-THALES"},
    {"id":"3Q11","units":3,"question":"במשולש ABC, AD חוצה זווית A. נתון AB=6, AC=9. מצא BD/DC.","template_hint":"T3-GEO-ANGLE-BISECTOR"},
    {"id":"3Q12","units":3,"question":"במשולש, נתון שתי צלעות וזווית כלולה. הוכח חפיפה בין שני משולשים.","template_hint":"T3-GEO-CONGRUENCE"},
    {"id":"3Q13","units":3,"question":"במעגל, זווית היקפית הנשענת על קוטר. מצא את הזווית.","template_hint":"T3-CIRCLE-ANGLES"},
    {"id":"3Q14","units":3,"question":"במעגל, זווית מרכזית היא 120°. מצא זווית היקפית הנשענת על אותה קשת.","template_hint":"T3-CIRCLE-ANGLES"},
    {"id":"3Q15","units":3,"question":"רדיוס מאונך למשיק בנקודת השקה. חשב זווית חסרה בתרשים משיק.","template_hint":"T3-CIRCLE-TANGENT"},
    {"id":"3Q16","units":3,"question":"שתי קוביות הוטלו. מה ההסתברות שסכום הנקודות 7?","template_hint":"T3-PROB-TREE-COUNT"},
    {"id":"3Q17","units":3,"question":"הוצאה קלף מחפיסה. מה ההסתברות לקבל לב?","template_hint":"T3-PROB-TREE-COUNT"},
    {"id":"3Q18","units":3,"question":"מטילים מטבע פעמיים. חשב הסתברות לקבל לפחות פעם אחת עץ.","template_hint":"T3-PROB-TREE-COUNT"},
    {"id":"3Q19","units":3,"question":"נתון P(A)=0.4, P(B)=0.5, P(A∩B)=0.2. מצא P(A|B).","template_hint":"T3-PROB-COND-BASIC"},
    {"id":"3Q20","units":3,"question":"במשולש ישר זווית: sin(θ)=0.6. מצא tan(θ).","template_hint":"T3-TRIG-RIGHT-TRI"}
];

export const sampleBank4Units = [
    {"id":"4Q01","units":4,"question":"חקור את הפונקציה f(x)=x^3-3x: תחום, קיצון, סקיצה.","template_hint":"T4-FUNC-INVEST-STD"},
    {"id":"4Q02","units":4,"question":"מצא תחום ואסימפטוטות של f(x)=(2x+1)/(x-3).","template_hint":"T4-FUNC-RATIONAL-ASYM"},
    {"id":"4Q03","units":4,"question":"פתור בתחום [0,2π]: cos(2x)=cos(x).","template_hint":"T4-TRIG-EQ-STD"},
    {"id":"4Q04","units":4,"question":"הוכח זהות: (1-sin^2x)=cos^2x.","template_hint":"T4-TRIG-ID-STD"},
    {"id":"4Q05","units":4,"question":"פתור: 2^x+2^{x+1}=24.","template_hint":"T4-EXPLOG-EQ"},
    {"id":"4Q06","units":4,"question":"פתור: log_2(x-1)+log_2(x+1)=3.","template_hint":"T4-EXPLOG-EQ"},
    {"id":"4Q07","units":4,"question":"חקור f(x)=ln(x)-x: תחום, קיצון.","template_hint":"T4-EXPLOG-FUNC"},
    {"id":"4Q08","units":4,"question":"נתון משיק ומיתר במעגל. השתמש בחזקת נקודה כדי למצוא אורך חסר.","template_hint":"T4-CIRCLE-POWER"},
    {"id":"4Q09","units":4,"question":"שני מיתרים נחתכים בתוך מעגל: AE·EB=CE·ED. מצא אורך חסר.","template_hint":"T4-CIRCLE-POWER"},
    {"id":"4Q10","units":4,"question":"בתרשים עם מקבילים, הוכח דמיון ומצא יחס דמיון.","template_hint":"T4-GEO-SIMILARITY-THALES"},
    {"id":"4Q11","units":4,"question":"במשולש ABC, AD חוצה זווית. נתון AB=8, AC=12, BD=4. מצא DC.","template_hint":"T4-GEO-ANGLE-BISECTOR"},
    {"id":"4Q12","units":4,"question":"שתי נקודות A(1,2), B(5,6). מצא שיפוע ומשוואת הישר AB.","template_hint":"T4-ANALYTIC-LINE"},
    {"id":"4Q13","units":4,"question":"מצא נקודת אמצע של קטע שקצותיו (−2,4) ו-(6,0), ומרחק בין הנקודות.","template_hint":"T4-ANALYTIC-LINE"},
    {"id":"4Q14","units":4,"question":"מצא מרכז ורדיוס של המעגל x^2+y^2-4x+6y+4=0.","template_hint":"T4-ANALYTIC-CIRCLE"},
    {"id":"4Q15","units":4,"question":"מצא נקודות חיתוך של הישר y=x עם המעגל x^2+y^2=10.","template_hint":"T4-ANALYTIC-CIRCLE"},
    {"id":"4Q16","units":4,"question":"X~Bin(n=8,p=0.25). חשב P(X=2) ו-E(X).","template_hint":"T4-PROB-BINOM"},
    {"id":"4Q17","units":4,"question":"נתונה טבלת שכיחויות. חשב ממוצע וסטיית תקן.","template_hint":"T4-STAT-MEAN-VAR"},
    {"id":"4Q18","units":4,"question":"חקור פונקציה רציונלית f(x)=(x+1)/(x^2-1): תחום, אסימפטוטות.","template_hint":"T4-FUNC-RATIONAL-ASYM"},
    {"id":"4Q19","units":4,"question":"פתור בתחום [0,2π]: sinx=1/2.","template_hint":"T4-TRIG-EQ-STD"},
    {"id":"4Q20","units":4,"question":"פתור: ln(x)+ln(x-1)=0.","template_hint":"T4-EXPLOG-EQ"}
];